--- #YAML:1.0
name:               ASP4x-Captcha
version:            0.002
abstract:           Imager-based CAPTCHA for your ASP4 web application.
author:
    - John Drago <jdrago_999@yahoo.com>
license:            perl
distribution_type:  module
test_requires:
    Test::More:       0
requires:
    Carp:             0
    ASP4:             1.024
    Router::Generic:  0.003
no_index:
    directory:
        - t
        - inc
generated_by:       Hand
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
